/**
 * NHN Cloud 제1회 + 제2회 통합 문제 은행 (총 120문항)
 * 단답형 문항들을 실제 시험지와 동일한 명확한 전체 문장으로 보강했습니다.
 */
const generateQuestions = () => {
    const qList = [
        // ==========================================
        // ▼ 제1회 기출문제 (완성형 문장 보강본 - 60문항)
        // ==========================================
        {"category": "클라우드 개념", "title": "사용자가 필요에 따라 자원을 자동으로 확장/축소할 수 있는 기능은 무엇인가?", "options": ["온디맨드 셀프서비스", "광범위한 네트워크 접근성", "리소스 풀링", "탄력성"], "answer": "탄력성", "explanation": "자원을 수요에 따라 자동 확장·축소하는 기능을 탄력성이라 함."},
        {"category": "클라우드 개념", "title": "다음 중 표준 클라우드 서비스 모델(SPI)에 포함되지 않는 것은?", "options": ["IaaS", "PaaS", "SaaS", "DaaS"], "answer": "DaaS", "explanation": "DaaS는 표준 서비스 모델(IaaS, PaaS, SaaS)에 포함되지 않음."},
        {"category": "클라우드 개념", "title": "다음 중 클라우드 컴퓨팅을 도입했을 때 얻을 수 있는 장점과 거리가 먼 것은?", "options": ["비용 효율성", "확장성", "유연성", "높은 초기 투자 비용"], "answer": "높은 초기 투자 비용", "explanation": "클라우드는 초기 투자를 낮추어 비용 효율성을 제공."},
        {"category": "클라우드 개념", "title": "클라우드 컴퓨팅 환경에서 '리소스 풀링(Resource Pooling)'이 의미하는 것은 무엇인가?", "options": ["자원을 직접 관리", "고정 할당", "다수 사용자에 동적 할당", "분산 저장"], "answer": "다수 사용자에 동적 할당", "explanation": "리소스 풀링은 제공자가 자원을 풀로 관리하고 동적으로 할당."},
        {"category": "클라우드 개념", "title": "외부와 격리되어 오직 단일 조직만을 위해 전용으로 구축 및 운영되는 클라우드 형태는?", "options": ["퍼블릭", "프라이빗", "하이브리드", "커뮤니티"], "answer": "프라이빗", "explanation": "프라이빗 클라우드는 단일 조직 전용으로 구축."},
        {"category": "책임 공유 모델", "title": "클라우드 보안 체계의 핵심인 '책임 공유 모델(Shared Responsibility Model)'의 기본 개념은?", "options": ["제공자 전담", "사용자 전담", "공유", "보안 미포함"], "answer": "공유", "explanation": "책임 공유 모델은 제공자와 사용자가 보안 책임을 분담."},
        {"category": "책임 공유 모델", "title": "IaaS(Infrastructure as a Service) 모델을 이용할 때 사용자가 직접 책임져야 하는 영역은?", "options": ["하드웨어", "데이터 보안", "물리적 보안", "네트워크 인프라"], "answer": "데이터 보안", "explanation": "IaaS 사용자는 OS, 애플리케이션, 데이터 보안을 담당."},
        {"category": "책임 공유 모델", "title": "책임 공유 모델에서 클라우드 서비스 제공자(Provider)가 전적으로 책임지는 보안 영역은?", "options": ["사용자 데이터", "애플리케이션", "물리적 인프라 보안", "접근 제어"], "answer": "물리적 인프라 보안", "explanation": "제공자는 물리적 호스트, 네트워크 인프라 보안을 책임짐."},
        {"category": "책임 공유 모델", "title": "PaaS(Platform as a Service) 환경에서 사용자가 직접 관리할 필요가 없는 항목은 무엇인가?", "options": ["애플리케이션 코드", "데이터", "운영 체제", "접근 제어"], "answer": "운영 체제", "explanation": "PaaS는 OS, 미들웨어 관리가 제공자 책임."},
        {"category": "책임 공유 모델", "title": "SaaS(Software as a Service) 서비스를 활용할 때 사용자가 부담해야 하는 주요 책임은?", "options": ["애플리케이션 유지보수", "데이터 관리", "서버 관리", "네트워크 관리"], "answer": "데이터 관리", "explanation": "SaaS 사용자는 주로 데이터 입력 및 관리를 담당."},
        {"category": "보안 개념", "title": "여러 고객이 인프라 자원을 공유하는 '다중 테넌시(Multi-Tenancy)' 환경에서 가장 우려되는 보안 문제는?", "options": ["데이터 중복", "서비스 중단", "데이터 격리 실패", "비용 증가"], "answer": "데이터 격리 실패", "explanation": "다중 테넌시 환경에서 테넌트 간 데이터 격리가 핵심."},
        {"category": "보안 개념", "title": "클라우드 저장소 및 네트워크 통신에서 데이터 암호화를 수행하는 가장 주된 목적은?", "options": ["압축", "전송 속도 향상", "무결성 보장", "기밀성 보장"], "answer": "기밀성 보장", "explanation": "암호화는 무단 접근으로부터 데이터 기밀성 유지."},
        {"category": "보안 개념", "title": "시스템 및 자원에 대한 접근 제어(Access Control) 메커니즘이 담당하는 주요 기능은 무엇인가?", "options": ["백업", "인증 및 권한", "속도 향상", "자동화"], "answer": "인증 및 권한", "explanation": "접근 제어는 사용자 인증·권한 부여를 담당."},
        {"category": "보안 개념", "title": "인프라의 잠재적인 보안 취약점을 선제적으로 식별하기 위해 수행하는 조치는 무엇인가?", "options": ["성능 최적화", "취약점 식별", "백업 검증", "확장성 검증"], "answer": "취약점 식별", "explanation": "침투 테스트는 모의 공격으로 보안 취약점 찾기."},
        {"category": "보안 개념", "title": "클라우드 시스템 운영에서 로깅(Logging) 및 모니터링 체계를 구축하는 가장 중요한 이유는?", "options": ["비용 절감", "이벤트 탐지", "가용성 증가", "대역폭 확보"], "answer": "이벤트 탐지", "explanation": "로깅·모니터링은 이상 행위 탐지 및 감사 추적에 필수."},
        {"category": "서비스 특징", "title": "NHN Cloud의 가용성 영역(Availability Zone)에 대한 설명 중 사실과 다른 것은?", "options": ["독립 지리적 위치", "여러 데이터 센터", "지연 매우 높음", "다중 AZ 배포 권장"], "answer": "지연 매우 높음", "explanation": "동일 리전 내 AZ 지연은 낮아 분산 배포에 적합."},
        {"category": "서비스 특징", "title": "NHN Cloud 리소스에 설정하는 '태그(Tag)' 정책의 주요 목적은 무엇인가?", "options": ["보안 그룹", "비용 분석", "이미지 빌더", "스케일링"], "answer": "비용 분석", "explanation": "태그를 사용해 자원 분류 및 비용 할당 분석."},
        {"category": "서비스 특징", "title": "NHN Cloud 프로젝트 내에서 생성 리소스 한도를 제한하는 '쿼터(Quota)' 설정 대상이 아닌 것은?", "options": ["인스턴스 생성 수", "VPC 개수", "SSH 키 개수", "미러링 세션 수"], "answer": "SSH 키 개수", "explanation": "SSH 키는 별도 제한 없이 관리."},
        {"category": "서비스 특징", "title": "기본 제공되는 리소스 제한(쿼터) 해제를 신청할 때, 작성할 필요가 없는 정보는?", "options": ["요청 사유", "예상 사용량", "결제 카드 정보", "리소스 유형"], "answer": "결제 카드 정보", "explanation": "결제 정보는 이미 등록되어 있어 추가 필요 없음."},
        {"category": "서비스 특징", "title": "NHN Cloud 정책 및 시스템 안정성을 위해 엄격히 제한되거나 허용되지 않는 행동은?", "options": ["공용 이미지", "과도한 API 호출", "모니터링", "사용자 태그"], "answer": "과도한 API 호출", "explanation": "과도한 호출은 서비스 안정성 해치므로 제한됨."},
        {"category": "Compute", "title": "NHN Cloud Compute 서비스에서 사용되는 '스펙 티어(Spec Tier)'가 의미하는 것은 무엇인가?", "options": ["대역폭 수준", "CPU·메모리 등급", "이미지 체계", "할인 구분"], "answer": "CPU·메모리 등급", "explanation": "스펙티어는 인스턴스 사양 등급 분류 기준."},
        {"category": "Compute", "title": "높은 IOPS와 대량의 읽기/쓰기 성능을 필요로 하는 워크로드에 가장 적절한 스토리지 유형은?", "options": ["싱크드라이브", "고성능 SSD", "저비용 HDD", "NFS"], "answer": "고성능 SSD", "explanation": "SSD 볼륨은 높은 IOPS 성능을 제공."},
        {"category": "Compute", "title": "머신러닝(ML) 인공지능 학습 및 추론 연산에 최적화된 인스턴스 유형은 무엇인가?", "options": ["웹 서버", "DB", "ML 학습/추론", "백업"], "answer": "ML 학습/추론", "explanation": "GPU 인스턴스는 병렬 연산에 최적화됨."},
        {"category": "Compute", "title": "NHN Cloud에서 제공하는 인스턴스의 상세 물리 GPU 세대 정보를 확인할 수 있는 위치는 어디인가?", "options": ["태그", "콘솔 사양 페이지", "ACL 규칙", "과금 내역"], "answer": "콘솔 사양 페이지", "explanation": "세대 정보는 인스턴스 상세 사양 화면에서 확인."},
        {"category": "Compute", "title": "가상 인스턴스의 구성 정보를 미리 정의하여 신속하고 동일한 사양의 인스턴스 배포를 돕는 리소스는?", "options": ["이미지 관리", "빠른 배포", "로깅 설정", "피어링"], "answer": "빠른 배포", "explanation": "템플릿으로 사전 정의된 설정 재사용 가능."},
        {"category": "Compute", "title": "이미 생성되어 있는 인스턴스 템플릿의 사양 설정을 업데이트(수정)할 경우 발생하는 현상으로 옳은 것은?", "options": ["기존 인스턴스", "다음 생성 사양", "대역폭", "과금 주기"], "answer": "다음 생성 사양", "explanation": "템플릿 수정은 이후 인스턴스 생성에만 반영."},
        {"category": "Compute", "title": "현재 운영 중인 인스턴스를 바탕으로 커스텀 이미지를 생성하고자 할 때, 데이터의 일관성(Consistency)을 보장하기 위해 선행되어야 하는 작업은?", "options": ["ACL 설정", "인스턴스 정지", "LB 연결", "게이트웨이 구성"], "answer": "인스턴스 정지", "explanation": "이미지 생성 전 정지해야 데이터 일관성 보장."},
        {"category": "Compute", "title": "생성한 커스텀 이미지의 퍼미션(공유 권한)을 설정하고 관리할 때 보안 사고를 막기 위해 가장 주의해야 하는 항목은?", "options": ["태그", "권한 설정", "리전", "알림"], "answer": "권한 설정", "explanation": "공개 이미지 권한 관리로 무단 접근 방지."},
        {"category": "Compute", "title": "운영체제(OS)와 기본 애플리케이션 빌드 단계를 자동화하여 안전한 최신 커스텀 이미지를 제작해주는 서비스는?", "options": ["VM 확장", "커스텀 이미지 제작", "DNS", "트래픽 분석"], "answer": "커스텀 이미지 제작", "explanation": "빌더로 OS·앱 포함 이미지 파이프라인 자동화."},
        {"category": "Compute", "title": "이미지 빌더(Image Builder) 서비스의 자동화 파이프라인 구성 단계에 포함되지 않는 것은?", "options": ["빌드", "테스트", "배포", "과금"], "answer": "과금", "explanation": "파이프라인 단계는 빌드·테스트·배포."},
        {"category": "Compute", "title": "오토 스케일링(Auto Scaling) 메커니즘에서 부하 증가에 대응하기 위해 자원(인스턴스 수)을 동적으로 추가하는 동작은?", "options": ["축소", "인스턴스 추가", "이미지 삭제", "네트워크 확장"], "answer": "인스턴스 추가", "explanation": "스케일 아웃은 부하 증가 시 인스턴스 수 확장."},
        {"category": "Compute", "title": "오토 스케일링 정책에서 빈번하고 과도한 자원 증감을 억제하기 위해 설정하는 '쿨다운(Cooldown)' 기간의 주된 도입 목적은?", "options": ["과금 조정", "잦은 스케일링 방지", "업데이트 지연", "동기화"], "answer": "잦은 스케일링 방지", "explanation": "쿨다운으로 빈번한 변동 억제."},
        {"category": "Network", "title": "다음 중 NHN Cloud의 격리된 네트워크 환경을 제공하는 VPC(Virtual Private Cloud) 고유 기능으로 보기 어려운 것은?", "options": ["네트워크 격리", "서브넷 분할", "퍼블릭 IP 자동", "NAT 제공"], "answer": "퍼블릭 IP 자동", "explanation": "퍼블릭 IP는 별도 Floating IP 서비스 사용."},
        {"category": "Network", "title": "라우팅 테이블 규칙에서 대상 경로가 '0.0.0.0/0'이고 타겟이 인터넷 게이트웨이(IGW)로 설정된 규칙의 의미는?", "options": ["내부 통신 허용", "모든 인터넷 트래픽", "프라이빗 경로", "피어링 종료"], "answer": "모든 인터넷 트래픽", "explanation": "0.0.0.0/0은 전체 대상, IGW로 전달."},
        {"category": "Network", "title": "VPC 내부 아키텍처에서 퍼블릭 서브넷(Public)과 프라이빗 서브넷(Private)을 나누는 핵심 기준은 무엇인가?", "options": ["서브넷 크기", "IGW 연결 여부", "CIDR 방식", "SG 적용"], "answer": "IGW 연결 여부", "explanation": "퍼블릭은 IGW 경로, 프라이빗은 없음."},
        {"category": "Network", "title": "프라이빗 서브넷 내부에 존재하는 인스턴스에 고정적인 외부 인터넷 접속 주소를 동적으로 바인딩해주는 리소스는?", "options": ["피어링", "동적 퍼블릭 IP", "DNS 갱신", "헬스체크"], "answer": "동적 퍼블릭 IP", "explanation": "Floating IP는 인스턴스에 퍼블릭 IP 제공."},
        {"category": "Network", "title": "인스턴스에 바인딩되어 사용 중이던 플로팅 IP(Floating IP)를 해제(Disassociate)했을 때 일어나는 현상으로 옳은 것은?", "options": ["즉시 삭제", "풀로 반환", "인스턴스 재부팅", "SG 삭제"], "answer": "풀로 반환", "explanation": "해제 시 IP는 재사용 풀로 돌아감."},
        {"category": "Network", "title": "다음 중 서브넷 단위로 적용되는 보안 옵션인 네트워크 ACL(Access Control List)의 설명으로 틀린 것은?", "options": ["서브넷 적용", "비저장", "SG 우선", "인/아웃 규칙"], "answer": "SG 우선", "explanation": "ACL과 SG는 각각 적용, 우선순위 개념 없음."},
        {"category": "Network", "title": "상태 비저장(Stateless) 방식으로 동작하는 네트워크 ACL 규칙을 수립할 때 보안 그룹(Stateful)과의 가장 큰 차이점은 무엇인가?", "options": ["응답도 허용 필요", "세션 계속 허용", "블록 단위만", "로깅 없음"], "answer": "응답도 허용 필요", "explanation": "Stateless ACL은 응답 트래픽도 별도 허용 설정."},
        {"category": "Network", "title": "인스턴스 레벨의 가상 방화벽 역할을 수행하는 보안 그룹(Security Group)의 특징 중 잘못된 것은?", "options": ["인스턴스 단위", "상태 저장", "양방향 규칙 필요", "기본 아웃바운드 허용"], "answer": "양방향 규칙 필요", "explanation": "SG는 인바운드 규칙만 설정해도 아웃바운드는 기본 허용."},
        {"category": "Network", "title": "보안 그룹 규칙(Security Group Rule)의 포트 범위 설정 항목에서 '0:65535'가 뜻하는 바는 무엇인가?", "options": ["모든 포트 차단", "모든 포트 허용", "ICMP만", "SSH만"], "answer": "모든 포트 허용", "explanation": "포트 범위 0-65535는 전체 허용 의미."},
        {"category": "Network", "title": "대규모 트래픽 분산과 인프라 서버들의 고가용성(High Availability) 환경을 보장하기 위해 도입하는 네트워크 서비스는?", "options": ["스토리지 확장", "트래픽 분산", "이미지 빌드", "모니터링"], "answer": "트래픽 분산", "explanation": "LB는 서버 간 부하 분산 및 고가용성 제공."},
        {"category": "Network", "title": "로드밸런서와 연동된 특정 백엔드 인스턴스가 헬스 체크(Health Check)에 연속으로 실패했을 때 나타나는 현상은?", "options": ["인스턴스 삭제", "분산 대상 제외", "SG 삭제", "알람 무시"], "answer": "분산 대상 제외", "explanation": "헬스체크 실패 인스턴스는 대상에서 제거."},
        {"category": "Network", "title": "복잡하고 거대한 대규모 다중 VPC 환경에서 허브(Hub) 역할을 수행하여 효율적인 상호 네트워크 연결을 제공하는 서비스는?", "options": ["피어링 대체", "이미지 저장", "스케일 정책", "CDN"], "answer": "피어링 대체", "explanation": "Transit Hub는 대규모 네트워크 허브 역할."},
        {"category": "Network", "title": "트랜짓 허브(Transit Hub)에서 라우팅 테이블 및 허브 경로를 설정하는 근본적인 목적이자 의미는 무엇인가?", "options": ["암호화", "리전 간 허브 경유", "피어링 자동", "SG 동기화"], "answer": "리전 간 허브 경유", "explanation": "설정 시 허브 통해 리전 간 트래픽 중계."},
        {"category": "Network", "title": "VPC 내부 사설망 리소스들이 외부 퍼블릭 인터넷과 양방향 통신이 가능하도록 경계선에 배치하는 네트워크 리소스는?", "options": ["피어링", "인터넷 접속", "DNS", "백업"], "answer": "인터넷 접속", "explanation": "IGW는 VPC-인터넷 양방향 연결 제공."},
        {"category": "Network", "title": "프라이빗 서브넷에 위치하여 퍼블릭 IP 주소가 존재하지 않는 인스턴스가 외부 인터넷 패치버전 등을 다운로드(아웃바운드 통신)하기 위해 거쳐야 하는 게이트웨이는?", "options": ["NAT Gateway", "LB", "Transit Hub", "SG"], "answer": "NAT Gateway", "explanation": "퍼블릭 IP 없는 프라이빗 인스턴스의 아웃바운드용."},
        {"category": "Network", "title": "NHN Cloud 아키텍처상 단일 VPC 내부에 인터넷 게이트웨이(IGW)를 복수로 연결(2개 이상 연결)하는 구성이 가능한가?", "options": ["예", "아니오"], "answer": "아니오", "explanation": "VPC당 IGW는 하나만 가능."},
        {"category": "Network", "title": "서로 다른 리전 혹은 서로 다른 계정에 소속된 두 VPC 간에 프라이빗 사설망 통신 경로를 다이렉트로 개설해주는 기능은?", "options": ["온프레 연결", "리전 VPC 간 트래픽", "서브넷 분할", "인터넷 라우팅"], "answer": "리전 VPC 간 트래픽", "explanation": "Peering은 리전/계정 다른 VPC 간 프라이빗 통신."},
        {"category": "Network", "title": "VPC 피어링(VPC Peering) 연결 시 적용되는 한계 및 제약 사항에 대한 설명 중 잘못된 것은?", "options": ["트랜짓 미지원", "SG 자동 동기화", "연결 수 제한", "경로 추가 필요"], "answer": "SG 자동 동기화", "explanation": "Peering은 네트워크만, SG는 개별 설정."},
        {"category": "Network", "title": "고객사의 온프레미스 물리 인프라 혹은 데이터센터와 NHN Cloud 환경을 하이브리드로 다이렉트 연동하는 네트워크 모델은?", "options": ["내부 통신", "하이브리드 네트워크", "CDN", "헬스체크"], "answer": "하이브리드 네트워크", "explanation": "Colocation은 온프레 데이터센터-클라우드 연결."},
        {"category": "Network", "title": "코로케이션(Colocation) 환경을 물리적으로 세팅하고 연동할 때 엔지니어가 필수로 확인하고 구성해야 하는 하드웨어 기본 정보는?", "options": ["VPC CIDR", "랙 위치·포트", "스케일 정책", "이미지 버전"], "answer": "랙 위치·포트", "explanation": "물리적 연결 정보가 필요."},
        {"category": "Network", "title": "NAT 게이트웨이(NAT Gateway) 서비스가 가상 네트워크 아키텍처 내부에서 수행하는 근본적인 역할은 무엇인가?", "options": ["프라이빗 인터넷", "퍼블릭 보호", "VPC 중계", "DNS"], "answer": "프라이빗 인터넷", "explanation": "NAT Gateway는 프라이빗 인스턴스 아웃바운드 지원."},
        {"category": "Network", "title": "VPC에 연결되어 동작 중이던 NAT 게이트웨이에 심각한 장애가 발생했을 때, 프라이빗 서브넷 리소스들이 받는 직접적인 타격은?", "options": ["퍼블릭만", "프라이빗 아웃바운드 차단", "모든 인바운드 차단", "피어링 중단"], "answer": "프라이빗 아웃바운드 차단", "explanation": "장애 시 외부로 나가는 트래픽만 차단됨."},
        {"category": "Network", "title": "공인 IP 주소를 할당받지 않고도 VPC 내부 사설망망을 거쳐 NHN Cloud 인프라 서비스 고유 API에 안전하게 직접 접근하도록 돕는 게이트웨이는?", "options": ["공인 IP 없이 서비스 접근", "CDN", "온프레 연결", "부하 분산"], "answer": "공인 IP 없이 서비스 접근", "explanation": "SGW로 내/외부망 없이 NHN Cloud 서비스 연결."},
        {"category": "Network", "title": "서비스 게이트웨이(Service Gateway)와 일반 NAT 게이트웨이가 처리하는 네트워크 트래픽 관점에서의 결정적인 차이점은 무엇인가?", "options": ["아웃바운드만", "프라이빗 전용", "인터넷 트래픽 처리 안 함", "동일 기능"], "answer": "인터넷 트래픽 처리 안 함", "explanation": "SGW는 클라우드 서비스 API 전용 라우팅만 처리."},
        {"category": "Network", "title": "특정 인스턴스나 서브넷의 네트워크 트래픽을 그대로 복제하여 보안 솔루션이나 패킷 분석 도구로 정밀 전달해주는 기능은 무엇인가?", "options": ["부하 분산", "트래픽 복제 전달", "CDN", "최적화"], "answer": "트래픽 복제 전달", "explanation": "보안·모니터링을 위해 지정 트래픽 복제."},
        {"category": "Network", "title": "트래픽 미러링(Traffic Mirroring) 대규모 모니터링 아키텍처를 프로덕션 환경에 설계할 때 엔지니어가 비용과 인프라 관점에서 가장 주의해야 하는 요인은?", "options": ["리전 간만", "같은 서브넷만", "성능·비용 고려", "항상 허용"], "answer": "성능·비용 고려", "explanation": "대량 복제로 대역폭 및 비용 증가 우려."},
        {"category": "Network", "title": "퍼블릭 공용 인터넷망을 우회하여 고객사 데이터센터와 클라우드 간의 전용 초고속 독립 회선을 다이렉트로 개설해주는 전용선 서비스는?", "options": ["암호화 인터넷", "전용 회선", "자동 피어링", "미러링"], "answer": "전용 회선", "explanation": "Direct Connect는 ISP 우회 전용 회선 제공."},
        {"category": "Network", "title": "전용 회선 링크를 구성하는 다이렉트 커넥트(Direct Connect) 서비스의 엔드포인트 물리 연결 유형에 해당하지 않는 것은?", "options": ["Hosted", "Dedicated", "Transit", "VPN"], "answer": "VPN", "explanation": "VPN은 인터넷 기반 암호화 연결, Direct Connect 유형 아님."},

        // ==========================================
        // ▼ 제2회 기출문제 (기존 완성형 문장 유지 - 60문항)
        // ==========================================
        {"category": "클라우드 개념", "title": "클라우드 컴퓨팅의 핵심 특징이 아닌 것은?", "options": ["온디맨드 셀프 서비스", "광대역 네트워크 접근성", "자원 과다 할당", "자원 풀링"], "answer": "자원 과다 할당", "explanation": "클라우드 컴퓨팅의 주요 특징은 자원 과다 할당이 아니라 \"자원 과다 할당 방지\"로, 효율적 자원 사용을 의미한다."},
        {"category": "클라우드 개념", "title": "책임 공유 모델에서 고객이 책임지는 항목은?", "options": ["물리적 데이터 센터 보안", "VM 하이퍼바이저 관리", "애플리케이션 설정과 데이터", "인프라 하드웨어 유지"], "answer": "애플리케이션 설정과 데이터", "explanation": "책임 공유 모델에서 고객은 애플리케이션 설정 및 데이터 관리를 책임진다."},
        {"category": "클라우드 개념", "title": "클라우드의 탄력성(elasticity)이란?", "options": ["고정 자원 배정", "자동 확장 및 축소", "미리 예약된 용량", "단일 장애 지점 제거"], "answer": "자동 확장 및 축소", "explanation": "탄력성(elasticity)은 수요에 따라 자원을 자동으로 확장하거나 축소하는 기능이다."},
        {"category": "클라우드 개념", "title": "Pay-as-you-go 요금제의 장점은?", "options": ["고정 월 사용료", "사용량 기반 과금", "초기 CapEx 증가", "모든 리소스 무제한 제공"], "answer": "사용량 기반 과금", "explanation": "Pay-as-you-go 모델은 사용량에 기반해 과금하므로 초기 투자(CapEx)를 줄일 수 있다."},
        {"category": "클라우드 개념", "title": "IaaS 서비스 예시는?", "options": ["서버리스 함수 실행", "가상 머신 인스턴스", "완전관리형 데이터베이스", "콘텐츠 전송 네트워크"], "answer": "가상 머신 인스턴스", "explanation": "IaaS는 가상 머신 인스턴스를 제공하는 서비스다."},
        {"category": "클라우드 개념", "title": "PaaS의 주요 이점은?", "options": ["OS 및 미들웨어 관리 면제", "인프라 완전 제어", "직접 하드웨어 관리", "고정 요금제만 지원"], "answer": "OS 및 미들웨어 관리 면제", "explanation": "PaaS는 OS 및 미들웨어 관리를 공급자가 제공해 고객이 코드 개발에 집중할 수 있다."},
        {"category": "클라우드 개념", "title": "클라우드 보안 모델에서 공급자 책임 항목은?", "options": ["데이터 암호화 설정", "네트워크 트래픽 관리", "하드웨어 및 물리 보안", "고객 애플리케이션 보안"], "answer": "하드웨어 및 물리 보안", "explanation": "클라우드 공급자는 하드웨어 및 물리적 보안을 책임진다."},
        {"category": "클라우드 개념", "title": "자원 풀링(resource pooling)이 의미하는 것은?", "options": ["전용 하드웨어 배정", "여러 고객 간 자원 공유", "고정 비용 청구", "중복 VM 제거"], "answer": "여러 고객 간 자원 공유", "explanation": "자원 풀링은 여러 고객이 공유 인프라에서 자원을 사용하는 개념이다."},
        {"category": "클라우드 개념", "title": "Defense in Depth 전략에 해당하지 않는 것은?", "options": ["네트워크 방화벽", "애플리케이션 코드 리뷰", "물리 서버 키 분실", "데이터 암호화"], "answer": "물리 서버 키 분실", "explanation": "Defense in Depth(다층 방어)에서 물리 서버 키 분실은 보안 전략이 아니다."},
        {"category": "클라우드 개념", "title": "클라우드 보안에서 무결성(integrity) 보장 방법은?", "options": ["디스크 암호화", "해시 검증(MAC)", "네트워크 ACL만", "단일 인증서 사용"], "answer": "해시 검증(MAC)", "explanation": "데이터 무결성 보장은 MAC(Message Authentication Code)과 같은 해시 검증 방식으로 수행한다."},
        {"category": "Compute", "title": "NHN Cloud의 가상 서버 상품명은?", "options": ["Cloud VM", "Bare Metal", "Cloud Function", "Cloud Server"], "answer": "Cloud Server", "explanation": "NHN Cloud 가상 서버는 \"Cloud Server\"로 명명된다."},
        {"category": "Compute", "title": "메모리 최적화 인스턴스 타입은?", "options": ["C1", "S2", "R2", "G1"], "answer": "R2", "explanation": "R2 타입은 메모리 최적화 인스턴스로, 메모리 집약적 워크로드에 적합하다."},
        {"category": "Compute", "title": "키 페어(Key Pair)의 구성요소가 아닌 것은?", "options": ["퍼블릭 키", "프라이빗 키", "대칭키", "암호화 알고리즘"], "answer": "대칭키", "explanation": "키 페어는 비대칭 암호화 방식으로 퍼블릭 키와 프라이빗 키로 구성된다."},
        {"category": "Compute", "title": "하이퍼바이저의 역할은?", "options": ["가상 머신의 물리 자원 공유", "네트워크 라우팅", "데이터베이스 관리", "로드밸런싱"], "answer": "가상 머신의 물리 자원 공유", "explanation": "하이퍼바이저는 물리 서버의 자원을 가상 머신에 분배 및 관리한다."},
        {"category": "Compute", "title": "오토스케일링 정책에 포함되지 않는 항목은?", "options": ["최소 인스턴스 수", "최대 인스턴스 수", "스케일링 조건", "애플리케이션 코드"], "answer": "애플리케이션 코드", "explanation": "오토스케일링 정책은 애플리케이션 코드가 아니라 인스턴스 수 및 조건 정의로 구성된다."},
        {"category": "Compute", "title": "오토스케일링 그룹에서 사용하는 템플릿은?", "options": ["Launch Template", "Backup Template", "Security Template", "Network Template"], "answer": "Launch Template", "explanation": "오토스케일링 그룹은 Launch Template을 사용해 인스턴스를 생성한다."},
        {"category": "Compute", "title": "Cloud Function 서비스는 어떤 유형인가?", "options": ["IaaS", "PaaS", "FaaS", "DBaaS"], "answer": "FaaS", "explanation": "Cloud Function은 Function as a Service(FaaS) 형태의 서버리스 컴퓨팅이다."},
        {"category": "Compute", "title": "서버리스 컴퓨팅의 대표적 장점은?", "options": ["고정 용량 예약", "코드만 배포", "하드웨어 직접 제어", "고정 요금제"], "answer": "코드만 배포", "explanation": "서버리스는 인프라 관리 없이 코드를 배포하여 실행할 수 있는 환경을 제공한다."},
        {"category": "Compute", "title": "이미지 기반 부팅(Local Boot Image) 장점은?", "options": ["빠른 스냅샷 복원", "자체 커널 사용", "CDN 배포 지원", "자동 백업"], "answer": "자체 커널 사용", "explanation": "Local Boot Image는 커스터마이징된 커널을 포함해 부팅 시간을 줄일 수 있다."},
        {"category": "Compute", "title": "VM 생성 시 필수 파라미터가 아닌 것은?", "options": ["--image-id", "--instance-type", "--region", "--billing-period"], "answer": "--billing-period", "explanation": "Billing-period는 VM 생성에 직접적으로 필요한 파라미터가 아니다."},
        {"category": "Compute", "title": "스팟 인스턴스의 특징은?", "options": ["사전 예약 요금", "낮은 우선순위 중단 가능", "무제한 사용 보장", "고정 SLA 제공"], "answer": "낮은 우선순위 중단 가능", "explanation": "스팟 인스턴스는 낮은 우선순위로 언제든 중단될 수 있는 특징이 있다."},
        {"category": "Compute", "title": "Floating IP의 역할은?", "options": ["사설 네트워크 제공", "공인 IP 할당", "VPC 피어링", "데이터 암호화"], "answer": "공인 IP 할당", "explanation": "Floating IP는 VM에 동적으로 공인 IP를 할당하는 기능이다."},
        {"category": "Compute", "title": "인스턴스 템플릿을 변경하려면 사용하는 서비스는?", "options": ["Cloud Config", "Cloud Trail", "Cloud Deploy", "Cloud Build"], "answer": "Cloud Config", "explanation": "Cloud Config는 인스턴스 부팅 시 설정을 자동화하는 서비스다."},
        {"category": "Compute", "title": "인스턴스를 아파트에 비유하는 이유는?", "options": ["월세 비용 때문", "자원 공유와 독립성 때문", "입주 조건 때문", "위치 기반 때문"], "answer": "자원 공유와 독립성 때문", "explanation": "아파트에 비유되는 이유는 공유 자원과 독립 환경을 동시에 제공하기 때문이다."},
        {"category": "Compute", "title": "VM 하드웨어 스펙 변경 시 필요한 작업은?", "options": ["VPC 재설정", "인스턴스 중지 후 타입 변경", "프로젝트 삭제", "보안 그룹 재설정"], "answer": "인스턴스 중지 후 타입 변경", "explanation": "VM 유형 변경은 인스턴스를 중지한 후 타입 변경 작업이 필요하다."},
        {"category": "Network", "title": "VPC에 할당하는 사설 IP 대역 예시는?", "options": ["192.0.2.0/24", "10.0.0.0/16", "8.8.8.0/24", "203.0.113.0/24"], "answer": "10.0.0.0/16", "explanation": "10.0.0.0/16은 사설 네트워크 대역으로 VPC에 자주 사용된다."},
        {"category": "Network", "title": "라우팅 테이블의 기본 경로를 나타내는 것은?", "options": ["127.0.0.1/32", "::/0", "0.0.0.0/0", "255.255.255.0"], "answer": "0.0.0.0/0", "explanation": "0.0.0.0/0은 모든 IPv4 주소를 의미하는 기본 경로(Default Route)다."},
        {"category": "Network", "title": "인터넷 게이트웨이 역할은?", "options": ["내부 통신 전용", "외부 인터넷 통신 중계", "DNS 관리", "VPC 삭제"], "answer": "외부 인터넷 통신 중계", "explanation": "인터넷 게이트웨이는 VPC와 인터넷 간 트래픽을 중계한다."},
        {"category": "Network", "title": "서브넷팅의 주된 목적은?", "options": ["속도 향상", "네트워크 분할 및 관리", "암호화", "로깅"], "answer": "네트워크 분할 및 관리", "explanation": "서브넷팅은 네트워크를 분할해 보안 및 관리를 용이하게 한다."},
        {"category": "Network", "title": "CIDR 표기법 \"192.168.1.0/24\"에서 /24 의미는?", "options": ["호스트 비트수", "네트워크 비트수", "서브넷 개수", "MAC 주소 길이"], "answer": "네트워크 비트수", "explanation": "/24는 네트워크 비트가 24비트임을 의미한다."},
        {"category": "Network", "title": "NAT의 주요 기능은?", "options": ["IP 충돌 탐지", "사설↔공인 IP 변환", "트래픽 암호화", "DNS 서비스"], "answer": "사설↔공인 IP 변환", "explanation": "NAT(Network Address Translation)는 사설 IP와 공인 IP를 상호 변환한다."},
        {"category": "Network", "title": "VPC 피어링의 목적은?", "options": ["인터넷 연결", "서로 다른 VPC 간 사설 연결", "CDN 배포", "로드밸런싱"], "answer": "서로 다른 VPC 간 사설 연결", "explanation": "VPC 피어링은 다른 VPC 간 프라이빗 통신을 가능하게 한다."},
        {"category": "Network", "title": "브로드캐스트 주소는 서브넷의 어떤 주소인가?", "options": ["첫 번째 주소", "마지막 주소", "중간 주소", "네트워크 주소"], "answer": "마지막 주소", "explanation": "브로드캐스트 주소는 서브넷의 마지막 주소이다."},
        {"category": "Network", "title": "라우터가 경로 결정에 참조하는 것은?", "options": ["DNS 테이블", "라우팅 테이블", "보안 그룹", "IAM 정책"], "answer": "라우팅 테이블", "explanation": "라우터는 라우팅 테이블을 참조해 패킷 경로를 결정한다."},
        {"category": "Network", "title": "기본 라우팅 테이블에 포함되는 경로는?", "options": ["외부 경로만", "내부(Local) 경로만", "외부 및 내부", "없음"], "answer": "외부 및 내부", "explanation": "기본 라우팅 테이블에는 내부(Local) 경로와 외부(Default) 경로가 모두 포함된다."},
        {"category": "Network", "title": "인터넷 접속을 위해 라우팅 테이블에 추가할 경로는?", "options": ["10.0.0.0/8→IGW", "::/0→IGW", "0.0.0.0/0→IGW", "255.255.0.0→IGW"], "answer": "0.0.0.0/0→IGW", "explanation": "인터넷 접속을 위해 0.0.0.0/0→IGW 경로를 추가한다."},
        {"category": "Network", "title": "Security Group은 어떤 계층에서 작동하는가?", "options": ["네트워크", "트랜스포트", "애플리케이션", "데이터링크"], "answer": "트랜스포트", "explanation": "Security Group은 트랜스포트 계층(TCP/UDP)에서 동작한다."},
        {"category": "Network", "title": "VPC 내 서브넷 간 통신이 가능한 이유는?", "options": ["인터넷 게이트웨이", "NAT", "기본 라우팅 테이블 내 로컬 경로", "VPN"], "answer": "기본 라우팅 테이블 내 로컬 경로", "explanation": "VPC 내 서브넷 간 통신은 기본 라우팅 테이블의 로컬 경로로 가능하다."},
        {"category": "Network", "title": "CIDR /30 서브넷 사용 가능 호스트 수는?", "options": ["2", "4", "6", "0"], "answer": "2", "explanation": "/30 서브넷은 2개의 유효 호스트 주소를 제공한다."},
        {"category": "Network", "title": "서브넷 마스크 255.255.255.0은 CIDR로?", "options": ["/16", "/24", "/32", "/8"], "answer": "/24", "explanation": "서브넷 마스크 255.255.255.0은 /24와 같다."},
        {"category": "Storage", "title": "Object Storage 주요 사용 사례는?", "options": ["블록 장치 연결", "대용량 비정형 데이터 저장", "SQL 쿼리 실행", "VM 이미지 백업"], "answer": "대용량 비정형 데이터 저장", "explanation": "객체 스토리지는 대용량 비정형 데이터를 저장하기 위해 사용된다."},
        {"category": "Storage", "title": "Block Storage의 특징은?", "options": ["파일 단위 접근", "VM 인스턴스 마운트 가능", "객체별 메타데이터 지원", "CDN 엣지 캐시"], "answer": "VM 인스턴스 마운트 가능", "explanation": "블록 스토리지는 VM에 마운트해 디스크처럼 사용 가능하다."},
        {"category": "Storage", "title": "Cloud Storage에 서명 URL(Signed URL)의 용도는?", "options": ["영구 공개 접근", "시간 제한된 접근 제어", "데이터 암호화", "네트워크 ACL 설정"], "answer": "시간 제한된 접근 제어", "explanation": "Signed URL은 시간 제한된 접근 권한을 제공한다."},
        {"category": "Database", "title": "NHN Cloud 완전관리형 관계형 DB 서비스는?", "options": ["Cloud SQL", "Cloud DB for MySQL", "Cloud Bigtable", "Cloud Spanner"], "answer": "Cloud DB for MySQL", "explanation": "Cloud DB for MySQL은 완전관리형 관계형 DB 서비스다."},
        {"category": "Database", "title": "RDS 자동 백업 기능 설정에 사용되는 것은?", "options": ["Snapshot Policy", "Backup Policy", "Restore Policy", "Log Shipping"], "answer": "Backup Policy", "explanation": "Backup Policy를 설정해 자동 백업 스케줄을 관리한다."},
        {"category": "Database", "title": "NoSQL 데이터 저장에 적합한 서비스는?", "options": ["Cloud DB for MySQL", "Cloud Bigtable", "Cloud SQL", "Cloud Spanner"], "answer": "Cloud Bigtable", "explanation": "Cloud Bigtable은 NoSQL 저장소에 적합하다."},
        {"category": "Security", "title": "Security Group의 기본 수신 규칙은?", "options": ["모두 허용", "모두 차단", "HTTP만 허용", "SSH만 허용"], "answer": "모두 차단", "explanation": "기본적으로 모든 인바운드 트래픽은 차단된다."},
        {"category": "Security", "title": "보안 그룹의 상태 저장(stateful)이 의미하는 것은?", "options": ["모든 설정 저장", "응답 트래픽 자동 허용", "로그 영구 저장", "재부팅 시 초기화"], "answer": "응답 트래픽 자동 허용", "explanation": "Stateful 보안 그룹은 응답 트래픽을 자동으로 허용한다."},
        {"category": "Security", "title": "네트워크 ACL(NACL)과 다른 점은?", "options": ["Stateful", "Regional", "사용자 기반", "계정 단위"], "answer": "Stateful", "explanation": "NACL은 Stateless, Security Group은 Stateful이다."},
        {"category": "Security", "title": "데이터 암호화를 위해 사용하는 것은?", "options": ["MAC 검증", "키 관리 서비스(KMS)", "보안 그룹", "IAM"], "answer": "키 관리 서비스(KMS)", "explanation": "KMS(Key Management Service)는 암호화 키를 관리한다."},
        {"category": "Security", "title": "책임 공유 모델에서 고객이 관리하지 않는 항목은?", "options": ["애플리케이션 보안", "운영체제 패치", "하드웨어 보안", "데이터 입력"], "answer": "하드웨어 보안", "explanation": "하드웨어 보안은 클라우드 공급자의 책임이다."},
        {"category": "Content Delivery", "title": "CDN의 주된 목적은?", "options": ["데이터베이스 분산", "지연 시간 단축", "VM 확장", "보안 그룹 관리"], "answer": "지연 시간 단축", "explanation": "CDN은 콘텐츠 전달 지연 시간을 줄인다."},
        {"category": "Content Delivery", "title": "CDN 원본(Origin) 역할은?", "options": ["캐시 서버", "실제 콘텐츠 제공 서버", "DNS 서비스", "로드밸런서"], "answer": "실제 콘텐츠 제공 서버", "explanation": "Origin은 실제 콘텐츠를 제공하는 원본 서버다."},
        {"category": "Content Delivery", "title": "CDN 엣지 캐시는 어디에 위치하는가?", "options": ["사용자 근처 PoP", "메인 리전", "고객 데이터 센터", "온프레미스 환경"], "answer": "사용자 근처 PoP", "explanation": "엣지 캐시는 사용자 근처의 PoP에 위치한다."},
        {"category": "Notification", "title": "NHN Cloud 메시징 서비스는?", "options": ["Cloud Pub/Sub", "Cloud Queue", "Cloud Stream", "Cloud Notify"], "answer": "Cloud Queue", "explanation": "NHN Cloud 메시징 서비스는 Cloud Queue다."},
        {"category": "Notification", "title": "메시지 브로커의 주요 사용 사례는?", "options": ["대용량 미디어 스트리밍", "비동기 작업 처리", "블록 스토리지 관리", "CDN 캐시 제어"], "answer": "비동기 작업 처리", "explanation": "메시지 브로커는 비동기 작업 처리에 사용된다."},
        {"category": "Notification", "title": "알림 서비스(Notification) 주요 기능은?", "options": ["트래픽 라우팅", "이벤트 기반 메시지 전송", "DB 백업", "VM 모니터링"], "answer": "이벤트 기반 메시지 전송", "explanation": "Notification 서비스는 이벤트 기반 메시지 전송을 지원한다."},
        {"category": "결재 및 요금", "title": "Pay-as-you-go 과금 방식의 특징은?", "options": ["선불 결제만", "사용량 기반 과금", "고정 월요금", "예약 인스턴스 전용"], "answer": "사용량 기반 과금", "explanation": "Pay-as-you-go는 사용량 기반 과금을 의미한다."},
        {"category": "결재 및 요금", "title": "NHN Cloud 크레딧 사용 순서는?", "options": ["부족분 먼저 차감", "크레딧 선차감 후 잔액 과금", "랜덤 차감", "유료 과금 선차감"], "answer": "크레딧 선차감 후 잔액 과금", "explanation": "크레딧은 먼저 차감되고 남은 금액이 과금된다."},
        {"category": "결재 및 요금", "title": "예약 인스턴스(Reserved VM) 장점은?", "options": ["단기 요금 할인", "장기 사용 요금 할인", "유연한 계약 해지", "무제한 용량 제공"], "answer": "장기 사용 요금 할인", "explanation": "예약 인스턴스는 장기 사용 시 할인 혜택을 제공한다."}
    ];

    return qList.map((q, index) => {
        return {
            id: index + 1,
            category: q.category,
            title: q.title,
            options: [...q.options].sort(() => Math.random() - 0.5), // 보기 순서 셔플 유지
            answer: q.answer,
            explanation: q.explanation
        };
    });
};

window.questions = generateQuestions();
